import { createElement } from '@lwc/engine-dom';
import Pubsub_lwc_subscriber_component_emp_details from 'c/pubsub_lwc_subscriber_component_emp_details';

describe('c-pubsub-lwc-subscriber-component-emp-details', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-pubsub-lwc-subscriber-component-emp-details', {
            is: Pubsub_lwc_subscriber_component_emp_details
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});