import { createElement } from '@lwc/engine-dom';
import Create_datatable_crypto_lwc_integrate from 'c/create_datatable_crypto_lwc_integrate';

describe('c-create-datatable-crypto-lwc-integrate', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-create-datatable-crypto-lwc-integrate', {
            is: Create_datatable_crypto_lwc_integrate
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});