import { createElement } from '@lwc/engine-dom';
import Lwc_delete_record_opp_without_apex from 'c/lwc_delete_record_opp_without_apex';

describe('c-lwc-delete-record-opp-without-apex', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-delete-record-opp-without-apex', {
            is: Lwc_delete_record_opp_without_apex
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});