import { createElement } from '@lwc/engine-dom';
import Get_record_lwc_imperation_without_apex from 'c/get_record_lwc_imperation_without_apex';

describe('c-get-record-lwc-imperation-without-apex', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-get-record-lwc-imperation-without-apex', {
            is: Get_record_lwc_imperation_without_apex
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});