import { createElement } from '@lwc/engine-dom';
import Lwc_c_to_p_employee_details_parent_component from 'c/lwc_c_to_p_employee_details_parent_component';

describe('c-lwc-c-to-p-employee-details-parent-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-c-to-p-employee-details-parent-component', {
            is: Lwc_c_to_p_employee_details_parent_component
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});