import { createElement } from '@lwc/engine-dom';
import Opp_lwc_wire_method_datatable from 'c/opp_lwc_wire_method_datatable';

describe('c-opp-lwc-wire-method-datatable', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-opp-lwc-wire-method-datatable', {
            is: Opp_lwc_wire_method_datatable
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});