import { createElement } from '@lwc/engine-dom';
import Pubsub_lwc_emp_details_publisher from 'c/pubsub_lwc_emp_details_publisher';

describe('c-pubsub-lwc-emp-details-publisher', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-pubsub-lwc-emp-details-publisher', {
            is: Pubsub_lwc_emp_details_publisher
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});