import { createElement } from '@lwc/engine-dom';
import Lwc_child_to_parent_p_vlc_player_example from 'c/lwc_child_to_parent_p_vlc_player_example';

describe('c-lwc-child-to-parent-p-vlc-player-example', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-child-to-parent-p-vlc-player-example', {
            is: Lwc_child_to_parent_p_vlc_player_example
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});