import { createElement } from '@lwc/engine-dom';
import Lwc_eg1_api_child_component from 'c/lwc_eg1_api_child_component';

describe('c-lwc-eg1-api-child-component', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-eg1-api-child-component', {
            is: Lwc_eg1_api_child_component
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});